### ISSUE TITLE
Allow user to pass in the vertical coordinate name

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/pyaxiom#1]
We would like the vertical coordinate variable name to be "z" instead of "height".  This would allow COARDS plotting programs like NCBROWSE to correctly show the CF-1.6 ADCP data (since dimension and coordinate variable would both be named "z".)

Looks like we could just change this one line here:
https://github.com/axiom-data-science/pyaxiom/blob/master/pyaxiom/netcdf/sensors/timeseries.py#L129

It looks like that would be sufficient to have the `coordinates` attributes be 
`time z lon lat` because of the nice coding here:
https://github.com/axiom-data-science/pyaxiom/blob/master/pyaxiom/netcdf/sensors/timeseries.py#L234

**Comment by kwilcox** [comment]
[This](https://github.com/axiom-data-science/pyaxiom/blob/5968c23c36871225eabd68aa572070dbc86edbba/pyaxiom/netcdf/sensors/timeseries.py#L129) value needs to be set from a parameter and default to 'height' for backwards compatibility and tests.

**Comment by rsignell-usgs** [comment]
CF requires that netcdf variable names are arbitrary, so why would you want to let the user assign this if using "z" will result in files that are compatible with more applications?  At the very least the default should be "z" instead of "height".
